name: urna_eletronica
description: "Urna Eletrônica - MVP em Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.4 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  # Persistência de senha
  shared_preferences: ^2.2.1
  # Exportação de arquivos TXT
  path_provider: ^2.0.15

  # Ícones iOS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets de imagens/fotos de candidatos (exemplo)
  # assets:
  #   - assets/images/background/
  #   - assets/images/candidates/
